# Generated by Django 3.1.2 on 2020-11-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotehere1', '0002_promote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promote',
            name='page_1',
            field=models.CharField(default='False', max_length=500),
        ),
        migrations.AlterField(
            model_name='promote',
            name='page_2',
            field=models.CharField(default='False', max_length=500),
        ),
        migrations.AlterField(
            model_name='promote',
            name='website_1',
            field=models.CharField(default='False', max_length=500),
        ),
        migrations.AlterField(
            model_name='promote',
            name='website_2',
            field=models.CharField(default='False', max_length=500),
        ),
    ]
