# Generated by Django 3.1.2 on 2020-11-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotehere1', '0003_auto_20201125_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promote',
            name='user_image',
            field=models.ImageField(upload_to='promotehere1/images'),
        ),
    ]
