# Generated by Django 3.2.5 on 2021-07-06 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_post_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video',
            new_name='videofile',
        ),
    ]
